name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  deployments: write
  packages: write

jobs:
  publish-dart:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Prepare Release Files
        working-directory: dart
        run: |
          cp ../Readme.md ./README.md
          cp ../LICENSE .
          cat <<< $(yq e -M ".version = \"${GITHUB_REF_NAME}\"" pubspec.yaml) > pubspec.yaml
      - name: Generate Changelog
        uses: ricardoboss/changelog-from-github-releases@v1
        with:
          file: dart/CHANGELOG.md
      - name: Release dry run
        working-directory: dart
        run: dart pub publish --dry-run
      - name: Release to pub.dev
        working-directory: dart
        run: dart pub publish --force
